### ISSUE TITLE
斗鱼的能看，哔哩哔哩的看不了

### ISSUE THREAD

**Issue by Wolfie-glitch** [thep0y/lsar#1]
b站的直播好像加密了，复制解析后的链接进potplater看不了。斗鱼的还行，可以看。

**Comment by thep0y** [comment]
可以用。
<img width="867" alt="image" src="https://user-images.githubusercontent.com/51874567/189459921-cf5e86ad-99e3-4245-bbaf-af439492efd9.png">

**Comment by Wolfie-glitch** [comment]
> 可以用。 <img alt="image" width="867" src="https://user-images.githubusercontent.com/51874567/189459921-cf5e86ad-99e3-4245-bbaf-af439492efd9.png">

那可能是potplayer的问题吧，对复制后的链接解不了码；谢谢啦。

**Comment by thep0y** [comment]
换mpv吧，mpv没有任何问题
