### ISSUE TITLE
简化cookie参数

### ISSUE THREAD

**Issue by playgithub** [thep0y/lsar#11]
yt-dlp指定浏览器以后可以自动获取cookie
`yt-dlp --cookies-from-browser chromium ...`

**Comment by thep0y** [comment]
这看起来是一件很复杂的事，python 有专门的库来从浏览器中获取加密的cookie并解密，node 上此类库较少，现有的库多数已陈旧。

考虑到时间成本，猴年马月以后再实现此功能。

**Comment by playgithub** [comment]
nodejs调用python
https://www.slingacademy.com/article/call-python-function-in-nodejs-app/
总之，不太完美，还是算了吧。

**Comment by playgithub** [comment]
nodejs调用python
https://www.slingacademy.com/article/call-python-function-in-nodejs-app/
总之，不太完美，还是算了吧。
