### ISSUE TITLE
# 很厉害,下面是我遇到的一些问题和解决（纯小白，大佬绕过）

### ISSUE THREAD

**Issue by XuXu-byte** [thep0y/lsar#3]
第一次发这个，搞得有点乱了哈哈。很好，斗鱼可以用（画质高又流畅）（为这个弄了半天，最后才找到这（就这个能用，其他的要么只能看几秒，要么都是垃圾获取源），但也弄了快一个小时）。一些建议，如果是纯小白（我也是）没接触过的话，直接cmd命令窗口敲，一条一条的来，缺什么bing什么（意思是哪出问题搜哪，缺啥补啥）。
步骤中要注意的（对小白）：装个node.js，好像必须在14以上，反正用最新的稳定版，然后把环境配置上。一般用msi装的就只用配node_moudles。然后按照步骤，没有npm、pnpm、yaml直接bing找，命令装就先行。然后在包管理器的第三步时，pnpm自己建一个（记住要配置环境），不要自动生成，没用。对了，项目提前下好，不用管克隆，然后项目目录指的是global里的（global里面有项目），然后直接走两步。记住，成功后要在项目目录运行这个去获取。好了，应该就这些，没接触过这个，
大佬绕过，有帮助就看看，没帮助就拜拜！（哈哈）

**Comment by thep0y** [comment]
之后会写一个新手教程，之前没想到会有小白用

**Comment by thep0y** [comment]
已添加新手教程
