### ISSUE TITLE
斗鱼直播源问题

### ISSUE THREAD

**Issue by silver-ka** [thep0y/lsar#6]
首选链接播放一段时间后会自动失效，而次选链接播放卡顿，请问有解决办法吗

**Comment by thep0y** [comment]
我又找到了一个新的解析方法，等更新后再试试吧。

毕竟不是官方支持，想要做到完美还是很难滴。

**Comment by Wolfie-glitch** [comment]
b站的好像也不行了，看一段时间后也卡掉了

**Comment by thep0y** [comment]
> b站的好像也不行了，看一段时间后也卡掉了

与斗鱼无关，应该开一个新的 issue

**Comment by thep0y** [comment]
新增的 pc 播放流实测观看一小时无波动、卡顿、断连现象。

<img width="1143" alt="image" src="https://github.com/thep0y/lsar/assets/51874567/6d334396-86e4-422a-9017-76f85c554718">
