### ISSUE TITLE
B站直播源的问题

### ISSUE THREAD

**Issue by Wolfie-glitch** [thep0y/lsar#7]
b站直播源获取不稳定，有时运行脚本获得的直播源数量都不一样；用VLC观看时，看个几分钟就会断线

**Comment by thep0y** [comment]
> b站直播源获取不稳定，有时运行脚本获得的直播源数量都不一样；用VLC观看时，看个几分钟就会断线

B 站直播源数量有变化的问题你最好能截张图说明，目前我没有发现不一致的可能性。

断线问题我已经试过了，看了5分钟，并未发生。

<img width="2032" alt="截屏2023-07-01 22 08 47" src="https://github.com/thep0y/lsar/assets/51874567/bb20e329-0ff9-4f36-9691-e55de0c10b7e">

我没有遇到的问题需要你提供更多的信息，包括但不限于截图、VLC日志。

**Comment by Wolfie-glitch** [comment]
应该是我网速的问题，我再研究看看，可能家里的wifi没开ipv6。

**Comment by upsetterlesson** [comment]
大佬，试试这个B站直播源“https://cn-cq-ct-01-10.bilivideo.com/live-bvc/971298/live_1438841525_53196379/index.m3u8”，我用VLC播放的，很卡顿。

**Comment by thep0y** [comment]
> 大佬，试试这个B站直播源“[https://cn-cq-ct-01-10.bilivideo.com/live-bvc/971298/live_1438841525_53196379/index.m3u8”，我用VLC播放的，很卡顿。](https://cn-cq-ct-01-10.bilivideo.com/live-bvc/971298/live_1438841525_53196379/index.m3u8%E2%80%9D%EF%BC%8C%E6%88%91%E7%94%A8VLC%E6%92%AD%E6%94%BE%E7%9A%84%EF%BC%8C%E5%BE%88%E5%8D%A1%E9%A1%BF%E3%80%82)

B站会为不同省份的用户分配不同的 cdn，你这个从链接上来看是重庆的 cdn，卡顿有可能是给你分配错了 cdn。

每个直播应该会解析出来 4 条播放源，一条卡很正常，如果 4 条都卡，你可以将看的直播的房间号发出来，我试试看。

下面是我播放的同一个房间的两个 cdn 的日志，一直有 3 秒的缓冲时间，播放到视频中的时间段未发现有卡顿：

https://github.com/thep0y/lsar/assets/51874567/6fdec3f6-17f4-4393-92bc-ed4dbdad611f

**Comment by upsetterlesson** [comment]
> > 大佬，试试这个B站直播源“[https://cn-cq-ct-01-10.bilivideo.com/live-bvc/971298/live_1438841525_53196379/index.m3u8”，我用VLC播放的，很卡顿。](https://cn-cq-ct-01-10.bilivideo.com/live-bvc/971298/live_1438841525_53196379/index.m3u8%E2%80%9D%EF%BC%8C%E6%88%91%E7%94%A8VLC%E6%92%AD%E6%94%BE%E7%9A%84%EF%BC%8C%E5%BE%88%E5%8D%A1%E9%A1%BF%E3%80%82)
> 
> B站会为不同省份的用户分配不同的 cdn，你这个从链接上来看是重庆的 cdn，卡顿有可能是给你分配错了 cdn。
> 
> 每个直播应该会解析出来 4 条播放源，一条卡很正常，如果 4 条都卡，你可以将看的直播的房间号发出来，我试试看。
> 
> 下面是我播放的同一个房间的两个 cdn 的日志，一直有 3 秒的缓冲时间，播放到视频中的时间段未发现有卡顿：
> 
>  input.mov

好的，我再试试，我还以为不同的源是不同的分辨率。
