### ISSUE TITLE
huya解析出来的结果不能播放。

### ISSUE THREAD

**Issue by happycode202** [thep0y/lsar#9]
lsar huya -r 676673

解析完成，任选一条下面的播放源，卡顿时可尝试切换其他播放源

房间名:
{
  flv: {
    '阿里': 'http://al.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=2098a7952918f03d29f38b9f6713b874&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735556&uid=1467033433464&uuid=2643300452',
    '腾讯': 'http://tx.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=641237fb6ab89405cfdd804a31b5b1eb&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735559&uid=1467033433464&uuid=2643303623',
    '华为': 'http://hw.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=edc0ba83dae91cd497fd98680ed95cb8&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735560&uid=1467033433464&uuid=2643304345'
  },
  hls: {
    '阿里': 'http://al.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=4ed37b7053ed58f4a387120adab919e4&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735558&uid=1467033433464&uuid=2643302570',
    '腾讯': 'http://tx.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=641237fb6ab89405cfdd804a31b5b1eb&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735559&uid=1467033433464&uuid=2643303820',
    '华为': 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=edc0ba83dae91cd497fd98680ed95cb8&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735560&uid=1467033433464&uuid=2643304997'
  }
}
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[16,22:11]
╰─ mpv  'http://al.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=2098a7952918f03d29f38b9f6713b874&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735556&uid=1467033433464&uuid=2643300452'
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://al.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=2098a7952918f03d29f38b9f6713b874&wsTime=65a7e012&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C&t=103&ver=1&sv=2110211124&seqid=3172447735556&uid=1467033433464&uuid=2643300452.
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl_hook] youtube-dl failed: unexpected error occurred

Exiting... (Errors when loading file)

**Comment by thep0y** [comment]
有一个不能用的时候要学会换其他的，我刚测试过，flv 阿里可能不能用了，但 flv 腾讯可以用。

```
mpv 'http://tx.flv.huya.com/src/1099531728421-1099531728421-86331612903505920-21
99063580298-10057-A-0-1-imgplus.flv?wsSecret=f4fd698387ddc031f39fa92e192bf7e8&wsTime=65a90556&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C264_8000%2C264_10000%2C264_20000%2C&t=103&ver=1&sv=2110211124&seqid=3172523136059&uid=1467033758414&uuid=409442428'
 (+) Video --vid=1 (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
     Subs  --sid=1 (text)
Using hardware decoding (videotoolbox).
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 videotoolbox[nv12]
```

如果你测试所有解析出来的源都不能播放，附上所有 mpv 错误截图，我会重新打个这个 issue。

**Comment by happycode202** [comment]
老哥，又不行了……
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:54]
╰─ lsar huya -r 676673
解析完成，任选一条下面的播放源，卡顿时可尝试切换其他播放源

房间名:
{
  flv: {
    '阿里': 'http://al.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=d6b6178758398ce2f102ad7448a44286&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702813&uid=1467408669470&uuid=2584216937',
    '腾讯': 'http://tx.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=d6b6178758398ce2f102ad7448a44286&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702813&uid=1467408669470&uuid=2584217094',
    '华为': 'http://hw.flv.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.flv?wsSecret=d6b6178758398ce2f102ad7448a44286&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702813&uid=1467408669470&uuid=2584217320'
  },
  hls: {
    '阿里': 'http://al.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=d6b6178758398ce2f102ad7448a44286&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702813&uid=1467408669470&uuid=2584217172',
    '腾讯': 'http://tx.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=d6b6178758398ce2f102ad7448a44286&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702813&uid=1467408669470&uuid=2584216704',
    '华为': 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
  }
}
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:57]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] NULL: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
 (+) Video --vid=1 (h264 1920x1080 40.000fps) (2560 kbps)
 (+) Audio --aid=1 (aac 2ch 44100Hz) (2560 kbps)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: keepalive request failed for 'http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&sub_m3u8=true&sv=2110211124&seqid=3181465702814&uid=1467408669470&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&user_session_id=f16478a995fd4adf95bef72e9383a134&uuid=2584217830&ctype=tars_mobile&edge_slice=true&fs=bgct&t=103&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&ver=1' with error: 'Server returned 403 Forbidden (access denied)' when parsing playlist
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
AV: 00:00:12 / 00:00:12 (100%) A-V:  0.000 Cache: 0.0s
Exiting... (End of file)
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:57]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830.
[ffmpeg] NULL: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
 (+) Video --vid=1 (h264 1920x1080 40.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
AV: 00:00:12 / 00:00:12 (100%) A-V:  0.000 Cache: 0.0s
Exiting... (End of file)
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:57]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830.
[ffmpeg] NULL: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
 (+) Video --vid=1 (h264 1920x1080 40.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
AV: 00:00:12 / 00:00:12 (100%) A-V:  0.000 Cache: 0.0s
Exiting... (End of file)
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:58]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: parse_playlist error Server returned 403 Forbidden (access denied) [http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?user_session_id=58a488787d5714003492f54ad9904874&wsTime=662bc0c8&ctype=tars_mobile&uuid=2584217830&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&edge_slice=true&sub_m3u8=true&t=103&wsSecret=ce08095e26c1f38c446a8e8dad6d396a]
[lavf] avformat_open_input() failed
[lavf] Leaking 1 nested connections (FFmpeg bug).
Playing: http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?edge_slice=true&user_session_id=bbd8d6d338d1d0ea019a5b2ee0584be8&t=103&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&ver=1&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&seqid=3181465702814&sv=2110211124&uid=1467408669470&sub_m3u8=true&uuid=2584217830
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?edge_slice=true&user_session_id=bbd8d6d338d1d0ea019a5b2ee0584be8&t=103&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&ver=1&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&seqid=3181465702814&sv=2110211124&uid=1467408669470&sub_m3u8=true&uuid=2584217830.
Exiting... (Some errors happened)
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:58]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830.
[ffmpeg] NULL: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
 (+) Video --vid=1 (h264 1920x1080 40.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
Cannot seek in this stream.
You can force it with '--force-seekable=yes'.
Cannot seek in this stream.
You can force it with '--force-seekable=yes'.
Cannot seek in this stream.
You can force it with '--force-seekable=yes'.
Cannot seek in this stream.
You can force it with '--force-seekable=yes'.
Cannot seek in this stream.
You can force it with '--force-seekable=yes'.
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Failed to reload playlist 0
AV: 00:00:12 / 00:00:12 (100%) A-V:  0.000 Cache: 0.0s
Exiting... (End of file)
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:58]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] http: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: parse_playlist error Server returned 403 Forbidden (access denied) [http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&edge_slice=true&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&exsphd=264_500%2C264_2000%2C264_4000%2C&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&t=103&sub_m3u8=true&sphdDC=huya&uuid=2584217830&sphd=264_*-265_*&user_session_id=9ae82f4756ff4f4503c74ad92f2f174c]
[lavf] avformat_open_input() failed
[lavf] Leaking 1 nested connections (FFmpeg bug).
Playing: http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&edge_slice=true&sub_m3u8=true&t=103&user_session_id=c2a552242ccae3b53d7e10d2f66e8f8d&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&exsphd=264_500%2C264_2000%2C264_4000%2C&wsTime=662bc0c8&uuid=2584217830
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&edge_slice=true&sub_m3u8=true&t=103&user_session_id=c2a552242ccae3b53d7e10d2f66e8f8d&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&exsphd=264_500%2C264_2000%2C264_4000%2C&wsTime=662bc0c8&uuid=2584217830.
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
[ytdl_hook] youtube-dl failed: unexpected error occurred
Exiting... (Some errors happened)
╭─[sunhl@DESKTOP-7MUVMBP]─[~]                                                                                                                ()─[25,22:59]
╰─ mpv 'http://hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?wsSecret=ce08095e26c1f38c446a8e8dad6d396a&wsTime=662bc0c8&ctype=tars_mobile&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&t=103&ver=1&sv=2110211124&seqid=3181465702814&uid=1467408669470&uuid=2584217830'
[ffmpeg] http: HTTP error 403 Forbidden
[lavf] avformat_open_input() failed
Playing: http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?uuid=2584217830&user_session_id=b992337da026427d9f90ab3900e6267e&ctype=tars_mobile&sub_m3u8=true&wsTime=662bc0c8&edge_slice=true&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&ver=1&sv=2110211124&t=103&seqid=3181465702814&fs=bgct&uid=1467408669470
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://a54b1deee602c6ce55d8a72a1b3b94dd.livehwc3.cn/hw.hls.huya.com/src/787262504-787262504-3381266708047069184-1574648464-10057-A-0-1.m3u8?uuid=2584217830&user_session_id=b992337da026427d9f90ab3900e6267e&ctype=tars_mobile&sub_m3u8=true&wsTime=662bc0c8&edge_slice=true&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500%2C264_2000%2C264_4000%2C&wsSecret=ce08095e26c1f38c446a8e8dad6d396a&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&ver=1&sv=2110211124&t=103&seqid=3181465702814&fs=bgct&uid=1467408669470.
Exiting... (Some errors happened)

**Comment by happycode202** [comment]
有的打不开，能打开的也只能播放十秒左右。

**Comment by thep0y** [comment]
等我有时间再看看能不能修复吧，虎牙可能更新了一些功能。

**Comment by happycode202** [comment]
> 等我有时间再看看能不能修复吧，虎牙可能更新了一些功能。

工作为重，有时间再说。

**Comment by happycode202** [comment]
可以参考https://github.com/liuchuancong/pure_live/releases
https://junlong.plus/ztool/live

**Comment by thep0y** [comment]
> 可以参考https://github.com/liuchuancong/pure_live/releases https://junlong.plus/ztool/live

你可以提交pr来适配虎牙

**Comment by 515664331** [comment]
C:\Users\LSW>lsar huya -r 660004
TypeError: Cannot read properties of null (reading '1')
    at t.getRoomInfo (C:\Users\LSW\AppData\Roaming\npm\node_modules\lsar\dist\apis\huya\index.js:1:816)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.printLiveLink (C:\Users\LSW\AppData\Roaming\npm\node_modules\lsar\dist\apis\huya\index.js:1:2473)

请问这个要怎么弄

**Comment by thep0y** [comment]
> C:\Users\LSW>lsar huya -r 660004 TypeError: Cannot read properties of null (reading '1') at t.getRoomInfo 
> 请问这个要怎么弄

虎牙需要修改，但我还没有时间（动力）适配。
